/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procedimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Clasificado extends javax.swing.JFrame {

    /**
     * Creates new form Clasificado
     */
    public Clasificado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtPalabras = new javax.swing.JTextField();
        txtTamaño = new javax.swing.JTextField();
        txtColores = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CLASIFICADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Numeros de Palabras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Tamalo en Centimetro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Numero de Colores");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("Total a Pagar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        txtPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabrasActionPerformed(evt);
            }
        });
        txtPalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabrasKeyTyped(evt);
            }
        });
        getContentPane().add(txtPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));

        txtTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoActionPerformed(evt);
            }
        });
        txtTamaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamañoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, -1));

        txtColores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoresKeyTyped(evt);
            }
        });
        getContentPane().add(txtColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 60, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamañoActionPerformed

    private void txtPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabrasActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        float tamaño, colores, palabras, total;
        String sumatoria;
    
     if(txtPalabras.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite el número de palabras","error", JOptionPane.ERROR_MESSAGE);
         txtPalabras.requestFocusInWindow();
         txtPalabras.selectAll();
     }
     else if(txtTamaño.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el tamaño en cm","error", JOptionPane.ERROR_MESSAGE);  
        txtTamaño.requestFocusInWindow();
        txtTamaño.selectAll();
     }  
     else if(txtColores.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la número de colores","error", JOptionPane.ERROR_MESSAGE);  
        txtColores.requestFocusInWindow(); 
         txtColores.selectAll();    
     }
     else{   
     palabras=Integer.parseInt(txtPalabras.getText());
     tamaño=Float.parseFloat(txtTamaño.getText());
     colores=Integer.parseInt(txtColores.getText());
         
    total=((palabras*20000)+(tamaño*15000)+(colores*25000));   
    
    sumatoria=String.valueOf(total);
    txtTotal.setText(sumatoria);
         
     }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
     txtPalabras.setText("");
     txtTamaño.setText("");
     txtColores.setText("");
     txtTotal.setText("");;
     txtPalabras.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtPalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabrasKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtPalabrasKeyTyped

    private void txtColoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoresKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtColoresKeyTyped

    private void txtTamañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamañoKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)&&evt.getKeyChar()!='.') {   
            getToolkit().beep();    
              evt.consume();   
          }
    if(evt.getKeyChar()=='.'&&txtTamaño.getText().contains(".")){
        evt.consume();
    }
    }//GEN-LAST:event_txtTamañoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clasificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clasificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clasificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clasificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clasificado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtColores;
    private javax.swing.JTextField txtPalabras;
    private javax.swing.JTextField txtTamaño;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
